# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "NikolaGrana" ]
  pull_request:
    branches: [ "NikolaGrana" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Clang and Clang-Tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang clang-tidy

      - name: Run Clang-Tidy
        run: clang-tidy src/**/*.cpp -- -Iinclude

  
  check_status:
    runs-on: ubuntu-latest
    needs: [lint]

    steps:
      - name: Check if any job failed
        run: |
          if [ ${{ job.status }} != 'completed' ]; then
            echo "::error::One or more jobs failed. Please fix the issues and try again."
            exit 1
          fi

      - name: Refuse Pull Request
        if: failure()
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               -d '{"state": "closed"}' \
               "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}"