# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Clang and Clang-Tidy
        run: |
          sudo apt-get update
          sudo apt-get install -y clang clang-tidy

      - name: Run Clang-Tidy
        run: clang-tidy src/**/*.cpp -- -Iinclude

  
  close_pull_request:
    if: failure()
    runs-on: ubuntu-latest

    needs: [lint]  # Add other job names if needed

    steps:
      - name: Install github-script
        run: npm install @actions/github-script

      - name: Close Pull Request on Failure
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.pulls.update({
              owner: Nik-Sub,
              repo: testRepository,
              pull_number: context.payload.pull_request.number,
              state: 'closed'
            });
            console.log(response);